### ISSUE TITLE
Redesign 404 page

### ISSUE THREAD

**Issue by anonimak** [anonimak/mipdevp-blog#2]
can someone help me to redesign 404 page more cool than before and match with theme?

**Comment by jsvigneshkanna** [comment]
I can take this, will work on 
Please assign me this issue

**Comment by anonimak** [comment]
go a head!

**Comment by SDtw20** [comment]
I can take this up

**Comment by DarkSoul26** [comment]
@anonimak I would like to work on this issue

**Comment by anonimak** [comment]
okay, there you go!

**Comment by SDtw20** [comment]
Hey, I've worked on this and created a pull request #4 
Sorry for informing late. I've attached a screenshot. Please do check it out.
<img width="1728" alt="Screenshot 2022-10-14 at 12 03 48 PM" src="https://user-images.githubusercontent.com/115735408/195778578-faebe7e7-0f9f-4dda-b9e8-7de2014f2ee2.png">

**Comment by anonimak** [comment]
@SDtw20 Thanks for the contribution, please read the [CONTRIBUTION](https://github.com/anonimak/mipdevp-blog/blob/master/CONTRIBUTION.md) before you do PR

**Comment by SDtw20** [comment]
@anonimak Sorry for that. Actually this is my first time contributing to OSS so didn't knew.

**Comment by DarkSoul26** [comment]
Shall I keep working on the same?

**Comment by anonimak** [comment]
sure @DarkSoul26

**Comment by SDtw20** [comment]
@DarkSoul26 Hey, if you're not working on this kindly consider giving me a chance

**Comment by DarkSoul26** [comment]
Sure @SDtw20 you can go for it

**Comment by SDtw20** [comment]
@anonimak can you please assign this to me

**Comment by anonimak** [comment]
okay

**Comment by SDtw20** [comment]
@anonimak Please check the PR #5 . I've added the overview of modification there.

**Comment by anonimak** [comment]
@SDtw20  thank you!
