### ISSUE TITLE
Latar belakang navigasi tidak konsisten

### ISSUE THREAD

**Issue by walfawalfa** [anonimak/mipdevp-blog#6]
Latar belakang navbar pada saat mode cerah atau gelap tidak konsisten. Pada saat mode cerah bentuknya solid dan menjadi transparan pada saat mode gelap.

Alangkah baiknya bila navbar lebih konsisten dalam mode gelap maupun cerah.

![Capture](https://user-images.githubusercontent.com/22593321/196134626-309156e2-d605-428a-925d-dd5f513db01e.PNG)

![Capture2](https://user-images.githubusercontent.com/22593321/196134656-38a41f80-79bf-468a-8cbf-bf81b4ff0030.PNG)

**Comment by anonimak** [comment]
udah ya

**Comment by anonimak** [comment]
[#f359f4](https://github.com/anonimak/mipdevp-blog/commit/f359f47481856c9a892934e10f0f260ba874ec83#commitcomment-87114337)
